name: ci

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  backend:
    name: "Backend (pytest + ruff)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps (ffmpeg)
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install ruff

      - name: Ruff (lint)
        run: ruff check backend

      - name: Pytest
        env:
          # không cần PIPER_* vì test đã monkeypatch
          PYTHONPATH: .
        run: |
          pytest -q

  frontend:
    name: "Frontend (typecheck + vitest)"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Enable corepack (pnpm)
        run: |
          corepack enable
          corepack prepare pnpm@9.0.0 --activate

      - name: Install deps
        run: pnpm -C frontend install --frozen-lockfile

      - name: Typecheck (tsc)
        run: pnpm -C frontend exec tsc --noEmit

      - name: Unit tests (vitest)
        run: pnpm -C frontend test
