name: preview-frontend

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install deps
        run: pnpm -C frontend install

      - name: Build
        env:
          # cho build dev-local; nếu có API public thì set VITE_API_BASE tương ứng
          VITE_API_BASE: http://localhost:8000/api
        run: pnpm -C frontend build

      - name: Upload artifact (dist)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
          if-no-files-found: error
